-- 1. Create Subscribers Table
CREATE TABLE IF NOT EXISTS public.subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.subscribers ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies
-- Allow anyone to subscribe (insert email)
CREATE POLICY "Allow public inserts on subscribers" ON public.subscribers FOR INSERT WITH CHECK (true);

-- Allow service role / admin to manage subscribers
CREATE POLICY "Allow service role read/write access to subscribers" ON public.subscribers FOR ALL USING (true) WITH CHECK (true);
