
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=https://whisk-wear.onrender.com/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
