-- Supabase Schema for Whiskwear E-Commerce (With User Authentication, Verification, Categories & Subcategories)
-- COPY AND RUN THIS ENTIRE SCRIPT IN YOUR SUPABASE SQL EDITOR.
-- WARNING: Running this will reset all products, categories, subcategories, users, and order logs.

-- 1. Reset / Clear Existing Tables and Policies
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.subcategories CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- 2. Create Users Table
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    is_verified BOOLEAN NOT NULL DEFAULT false,
    verification_code TEXT,
    code_expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Categories Table
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Subcategories Table
CREATE TABLE public.subcategories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(name, category_id)
);

-- 5. Create Products Table
CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('kitchen_cloths', 'kids_wear')),
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    subcategory_id BIGINT REFERENCES public.subcategories(id) ON DELETE SET NULL,
    image_urls TEXT[] NOT NULL DEFAULT '{}',
    stock INTEGER NOT NULL DEFAULT 0,
    is_featured BOOLEAN NOT NULL DEFAULT false,
    sales_count INTEGER NOT NULL DEFAULT 0,
    discount_percent INTEGER NOT NULL DEFAULT 0,
    sizes TEXT[] NOT NULL DEFAULT '{}',
    colors TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Create Orders Table
CREATE TABLE public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    customer_address TEXT NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'shipped', 'delivered', 'cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Create Order Items Table
CREATE TABLE public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    price NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subcategories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- 9. Create Policies
-- Users Policies
CREATE POLICY "Allow public signup on users" ON public.users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role read/write access to users" ON public.users FOR ALL USING (true) WITH CHECK (true);

-- Categories Policies
CREATE POLICY "Allow public select on categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Allow all operations for authenticated/service role on categories" ON public.categories FOR ALL USING (true) WITH CHECK (true);

-- Subcategories Policies
CREATE POLICY "Allow public select on subcategories" ON public.subcategories FOR SELECT USING (true);
CREATE POLICY "Allow all operations for authenticated/service role on subcategories" ON public.subcategories FOR ALL USING (true) WITH CHECK (true);

-- Products Policies
CREATE POLICY "Allow public select on products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Allow all operations for authenticated/service role on products" ON public.products FOR ALL USING (true) WITH CHECK (true);

-- Orders Policies
CREATE POLICY "Allow public inserts on orders" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role read/write access to orders" ON public.orders FOR ALL USING (true) WITH CHECK (true);

-- Order Items Policies
CREATE POLICY "Allow public inserts on order_items" ON public.order_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow service role read/write access to order_items" ON public.order_items FOR ALL USING (true) WITH CHECK (true);

-- 10. Seed Categories
INSERT INTO public.categories (name) VALUES 
('Kitchen Cloths'),
('Kids Wear')
ON CONFLICT (name) DO NOTHING;

-- 11. Seed Subcategories
INSERT INTO public.subcategories (name, category_id) VALUES
('Towels', (SELECT id FROM public.categories WHERE name = 'Kitchen Cloths')),
('Aprons', (SELECT id FROM public.categories WHERE name = 'Kitchen Cloths')),
('Dish Rags', (SELECT id FROM public.categories WHERE name = 'Kitchen Cloths')),
('Oven Mitts', (SELECT id FROM public.categories WHERE name = 'Kitchen Cloths')),
('Shirts', (SELECT id FROM public.categories WHERE name = 'Kids Wear')),
('Pants', (SELECT id FROM public.categories WHERE name = 'Kids Wear')),
('Shoes', (SELECT id FROM public.categories WHERE name = 'Kids Wear')),
('Dresses', (SELECT id FROM public.categories WHERE name = 'Kids Wear')),
('Rompers', (SELECT id FROM public.categories WHERE name = 'Kids Wear')),
('Pajamas', (SELECT id FROM public.categories WHERE name = 'Kids Wear'))
ON CONFLICT (name, category_id) DO NOTHING;

-- 12. Seed Products
INSERT INTO public.products (name, description, price, category, category_id, subcategory_id, image_urls, stock, is_featured, sales_count, discount_percent, sizes, colors) VALUES
('Classic Waffle Weave Towels', 'Pack of 4 super absorbent, 100% cotton kitchen towels. Ideal for drying dishes and hands.', 14.99, 'kitchen_cloths', 
 (SELECT id FROM public.categories WHERE name = 'Kitchen Cloths'),
 (SELECT id FROM public.subcategories WHERE name = 'Towels' AND category_id = (SELECT id FROM public.categories WHERE name = 'Kitchen Cloths')),
 ARRAY['https://images.unsplash.com/photo-1590794056226-79ef3a814c2c?w=600'], 50, true, 45, 15, ARRAY['Standard'], ARRAY['#dcdde1', '#f5f6fa']),

('Organic Cotton Baby Romper', 'Ultra-soft knit romper with snap closures for easy dressing. Made from 100% organic combed cotton.', 24.99, 'kids_wear', 
 (SELECT id FROM public.categories WHERE name = 'Kids Wear'),
 (SELECT id FROM public.subcategories WHERE name = 'Rompers' AND category_id = (SELECT id FROM public.categories WHERE name = 'Kids Wear')),
 ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600'], 30, true, 25, 0, ARRAY['6M', '12M', '18M', '24M'], ARRAY['#fbc531', '#4cd137', '#00a8ff']),

('Kids Denim Dungarees', 'Classic denim dungarees with adjustable straps and reinforced stitching. Built for active play.', 34.50, 'kids_wear', 
 (SELECT id FROM public.categories WHERE name = 'Kids Wear'),
 (SELECT id FROM public.subcategories WHERE name = 'Pants' AND category_id = (SELECT id FROM public.categories WHERE name = 'Kids Wear')),
 ARRAY['https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=600'], 20, false, 12, 20, ARRAY['2T', '3T', '4T', '5T'], ARRAY['#1b1464', '#0652dd']),

('Pastel Cotton Pajama Set', 'Two-piece pajama set with elastic waistband. Soft, breathable, and snug-fit for cozy nights.', 27.99, 'kids_wear', 
 (SELECT id FROM public.categories WHERE name = 'Kids Wear'),
 (SELECT id FROM public.subcategories WHERE name = 'Pajamas' AND category_id = (SELECT id FROM public.categories WHERE name = 'Kids Wear')),
 ARRAY['https://images.unsplash.com/photo-1515488042361-404e9250afef?w=600'], 30, true, 38, 10, ARRAY['2T', '3T', '4T', '5T'], ARRAY['#ffc0cb', '#e8a7a1', '#d4f0f0'])
ON CONFLICT DO NOTHING;
